# Generated by Django 4.1.7 on 2023-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
