# Generated by Django 4.1.7 on 2023-04-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
