# Generated by Django 4.1.7 on 2023-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.AddField(
            model_name='media',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='text'),
        ),
    ]
