# Generated by Django 4.1.7 on 2023-04-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_media_user_media_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
